### ISSUE TITLE
No license

### ISSUE THREAD

**Issue by nonbasketless** [jamesgregson/remesher#2]
I know I know, this is experimental code which you're not taking seriously, but it actually works pretty good. Like Meshlab level but fewer params. Easily better than https://github.com/huxingyi/isotropicremesher

But. Wondering what the license is?

**Comment by jamesgregson** [comment]
Hi Ben, glad to hear! As you say it’s not something I’m supporting, it was to try out a few sentence description of a remeshing strategy I read in a long forgotten (to me anyway) paper.However, if people find it useful I don’t want to needlessly lock it down for lack of a license. I will update it to be MIT.

**Comment by nonbasketless** [comment]
Thank you kindly mister.
